#%RAML 1.0 DataType
version:0.8.0
types:
	FlatGeometry:
		type: object
		properties:
			id:
        type: string
			crs:
        type: string
			wkt:
        type: string
        required: true
		example:{"id":"my-id","crs": "WGS84","wkt":"POLYGON((-4.7764560451359985 37.73318649600941, ...))"				}

	OperationData:
    type: object
    properties:
			sourceData:
				type: FlatGeometry[]
				uniqueItems: true
			overlayData:
				type: FlatGeometry[]
				uniqueItems: true
		example:{"sourceData":[{"id":"id-0",crs":"WGS84","wkt":"POLYGON((-4.7577667236328125 37.636202454188854,...))"},{"id":"id-1","crs":"WGS84","wkt":"POLYGON((-4.7687530517578125 37.633483617951576,))"}],"overlayData":[{"id":"id-2","crs":"WGS84","wkt":"POLYGON((-4.634513854980469 37.63147161675051,...))"},{"id":"id-3","crs":"WGS84","wkt":"POLYGON((-4.7577667236328125 37.636202454188854,...))"},{"id":"id-4","crs":"WGS84","wkt":"POLYGON((-4.7687530517578125 37.633483617951576,...))"}]}

  DivisionData:
		type: object
		properties:
			geomToDivide:
				type: FlatGeometry
			divisionLine:
				type: FlatGeometry
		example:{"geomToDivide":{"id":"id-0",crs":"WGS84","wkt":"POLYGON((-4.7577667236328125 37.636202454188854,...))"},"divisionLine":{"id":"id-0",crs":"WGS84","wkt":"LINESTRING (-6.210259817917375 38.259416305016615,...)"}}

  ErrorEntity:
  	type: object
    properties:
      id:
        type: number
      code:
        type: string
      status:
        type: string
    	title:
        type: string
      detail:
        type: string
      source:
        type: string
      link:
        type: string
    example:{
    			"id":11,
          "code":"BR.409",
    			"status":"409",
    			"title":"Validation Fail.",
    			"detail":"Can not be null",
    			"source":"Unprocessable Entity: ",
    			"link":"TODO: Error documentation"
    			}
   ValidationResult:
    type:object
    properties:
      id:
        type:boolean
      validatedFlatGeometry:
        type:FlatGeometry
      errors:
        type:ValidationErrorData[]
    example:{
          "valid": false,
          "validatedFlatGeometry": {"id": "1", "crs": "EPSG:3857","wkt": "POLYGON((-716727.93313342 5097076.7274115,-237314.89181468 4999237.331224,-863487.02741468 4710611.1124709,-144367.46543655 4651907.4747584,-716727.93313342 5097076.7274115))"},
          "errors": [{ "id": 401, "description": "Topological Error"}]
          }

  ValidationErrorData:
    type:object
    properties:
      id:
        type:number
      description:
        type:string
    example:{ "id": 401, "description": "Topological Error"}